### ISSUE TITLE
Implement drag and drop in redux

### ISSUE THREAD

**Issue by antonlopez** [WycliffeAssociates/translationExchange#255] opened 2017-09-07 13:40 UTC
## User Story
As a developer I want to implement the drag and drop code in redux so that the data manipulation can be done in  the store of redux and the drag and drop feature implementation in react. 

## Acceptance criteria
- [ ] Most of the states in components and props passed between components should be states allocated in the store at redux.

## Tasks
- [ ] Create reducers
- [ ] Create actions
- [ ] Refactor the code

**Comment by Redmayspecial** [comment] 2017-09-27 19:54
Closing as duplicate of #272

**Closed** 2017-09-27 19:54 UTC
Labels: duplicate, Front End
